# This Action uses minimal steps to run in ~5 seconds to rapidly:
# Build Scalable Vector Graphics (SVG) files of a set of dominoes plus a blank domino.
# Uses: https://pypi.org/project/svgwrite and https://github.com/prettier/plugin-xml
name: dominoes_svg
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  dominoes_svg:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
    - run: pip install --user svgwrite
    # - run: npm install --same-dev prettier @prettier/plugin-xml
    - run: |
        # git checkout -b "dominoes_svg_$(date +'%Y_%m_%d_%H_%M')"
        cd games/dominos
        mkdir -p dominoes_svg
        ls -l dominoes_svg
        python3 dominoes_svg.py
        ls -l dominoes_svg
        # ./node_modules/.bin/prettier --plugin=@prettier/plugin-xml --write dominoes_svg/domino_*.svg
        # npx prettier --plugin=@prettier/plugin-xml --write dominoes_svg/domino_*.svg
        # npx --package=@prettier/plugin-xml prettier --plugin=@prettier/plugin-xml --write dominoes_svg/domino_*.svg
        npx prettier --write dominoes_svg/domino_*.svg
    - uses: peter-evans/create-pull-request@v6
      with:
        commit-message: Recreate the Dominos Scalable Vector Graphics (SVG) files
